# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daniel de Mercado - Mi blog         #Aquí se usa una "-" para que el nombre aparezca así en la búsqueda de google.
email: danieldemercado.contacto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ¡Bienvenido a mi blog! Aquí escribo sobre física y otras ciencias, tecnología, economía, bitcoin... ¡y sobre cualquier otro tema que me 
  interese en ese momento!
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: danieldemercado
github_username:  danieldemercado



# Fields minima uses, but are not defaulted with the jekyll new command.
#Author is the default for posts, the Atom feed, and is used in the footer.
author: Daniel de Mercado
linkedin_username: danieldemercado
youtube_username: UC7lsg439P2qsLuFa6Gm5RSw



# New fields not defaulted by jekyll-new wiht the minima theme
# Add a copyright. A copyright symbol and year will be added automatically
copyright: "Daniel de Mercado"

# --- Donations methods -----
bitcoin_tippin_me_card: danieldemercado


# Build settings
# Removed minima theme as it is now a regular theme.
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap    #Añadido para crear sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
